#!/usr/bin/env swift
import Foundation

var table: [String: String] = [:]

// Scans local CoreSimulator profiles.
let profilesURL = URL(fileURLWithPath: "/Library/Developer/CoreSimulator/Profiles/DeviceTypes")
if let bundles = try? FileManager.default.contentsOfDirectory(at: profilesURL, includingPropertiesForKeys: nil) {
    for bundle in bundles where bundle.pathExtension == "simdevicetype" {
        let profilePlistURL = bundle.appendingPathComponent("Contents/Resources/profile.plist")
        let infoPlistURL = bundle.appendingPathComponent("Contents/Info.plist")

        var marketingName: String? = if let infoData = try? Data(contentsOf: infoPlistURL),
                                        let infoPlist = try? PropertyListSerialization.propertyList(
                                            from: infoData,
                                            options: [],
                                            format: nil
                                        ) as? [String: Any],
                                        let name = infoPlist["CFBundleName"] as? String {
            name
        } else {
            bundle.deletingPathExtension().lastPathComponent
        }

        if let profileData = try? Data(contentsOf: profilePlistURL),
           let profilePlist = try? PropertyListSerialization.propertyList(from: profileData, options: [], format: nil) as? [String: Any],
           let modelID = profilePlist["modelIdentifier"] as? String,
           let name = marketingName {
            table[modelID] = name
        }
    }
}

// Adds historical names from DeviceKit's MIT-licensed table.
let deviceKitBaseline: [String: String] = [
    "iPhone1,1": "iPhone",
    "iPhone1,2": "iPhone 3G",
    "iPhone2,1": "iPhone 3GS",
    "iPhone3,1": "iPhone 4",
    "iPhone3,2": "iPhone 4",
    "iPhone3,3": "iPhone 4",
    "iPhone4,1": "iPhone 4S",
    "iPhone5,1": "iPhone 5",
    "iPhone5,2": "iPhone 5",
    "iPhone5,3": "iPhone 5c",
    "iPhone5,4": "iPhone 5c",
    "iPhone6,1": "iPhone 5s",
    "iPhone6,2": "iPhone 5s",
    "iPhone7,1": "iPhone 6 Plus",
    "iPhone7,2": "iPhone 6",
    "iPhone8,1": "iPhone 6s",
    "iPhone8,2": "iPhone 6s Plus",
    "iPhone8,4": "iPhone SE",
    "iPhone9,1": "iPhone 7",
    "iPhone9,2": "iPhone 7 Plus",
    "iPhone9,3": "iPhone 7",
    "iPhone9,4": "iPhone 7 Plus",
    "iPhone10,1": "iPhone 8",
    "iPhone10,2": "iPhone 8 Plus",
    "iPhone10,3": "iPhone X",
    "iPhone10,4": "iPhone 8",
    "iPhone10,5": "iPhone 8 Plus",
    "iPhone10,6": "iPhone X",
    "iPhone11,2": "iPhone XS",
    "iPhone11,4": "iPhone XS Max",
    "iPhone11,6": "iPhone XS Max",
    "iPhone11,8": "iPhone XR",
    "iPhone12,1": "iPhone 11",
    "iPhone12,3": "iPhone 11 Pro",
    "iPhone12,5": "iPhone 11 Pro Max",
    "iPhone12,8": "iPhone SE (2nd generation)",
    "iPhone13,1": "iPhone 12 mini",
    "iPhone13,2": "iPhone 12",
    "iPhone13,3": "iPhone 12 Pro",
    "iPhone13,4": "iPhone 12 Pro Max",
    "iPhone14,2": "iPhone 13 Pro",
    "iPhone14,3": "iPhone 13 Pro Max",
    "iPhone14,4": "iPhone 13 mini",
    "iPhone14,5": "iPhone 13",
    "iPhone14,6": "iPhone SE (3rd generation)",
    "iPhone14,7": "iPhone 14",
    "iPhone14,8": "iPhone 14 Plus",
    "iPhone15,2": "iPhone 14 Pro",
    "iPhone15,3": "iPhone 14 Pro Max",
    "iPhone15,4": "iPhone 15",
    "iPhone15,5": "iPhone 15 Plus",
    "iPhone16,1": "iPhone 15 Pro",
    "iPhone16,2": "iPhone 15 Pro Max",
    "iPhone17,1": "iPhone 16 Pro",
    "iPhone17,2": "iPhone 16 Pro Max",
    "iPhone17,3": "iPhone 16",
    "iPhone17,4": "iPhone 16 Plus",
    "iPhone18,1": "iPhone 17 Pro",
    "iPhone18,2": "iPhone 17 Pro Max",
    "iPhone18,3": "iPhone 17",
    "iPhone18,4": "iPhone 17 Slim"
]

for (key, val) in deviceKitBaseline where table[key] == nil {
    table[key] = val
}

let sortedKeys = table.keys.sorted()

var output = """
// Generated by scripts/generate-device-table.swift. Do not edit directly.
import Foundation

public enum DeviceIdentifierTable: Sendable {
    public static let mapping: [String: String] = [

"""

let entries = sortedKeys.map { key -> String in
    let escapedVal = table[key]!.replacingOccurrences(of: "\"", with: "\\\"")
    return "        \"\(key)\": \"\(escapedVal)\""
}

output += entries.joined(separator: ",\n")
output += "\n"

output += """
    ]

    public static func lookup(_ identifier: String) -> String? {
        mapping[identifier]
    }
}
"""
output += "\n"

let destination = URL(fileURLWithPath: "CruftlessCore/Sources/CruftlessCore/Naming/DeviceIdentifierTable.swift")
try output.write(to: destination, atomically: true, encoding: .utf8)
print("Generated \(table.count) entries in \(destination.path)")
